name: 'Publish Conda'
description: 'Build and Publish Conda package to Anaconda'
author: 'Fatih C Akyon; Heliton Martins'
branding:
  icon: 'package'  
  color: 'purple'
inputs: 
  subdir:
    description: 'Sub-directory with conda recipe'
    default: '.'
  anacondatoken:
    description: 'Anaconda access token'
  platforms:
    description: 'Platforms to publish [osx/linux/win]'
    default: 'win osx linux'
  additional_params:
    description: 'Additional parameters to pass to conda build'
    default: ''
  label:
    description: 'Label for the conda package (see https://docs.anaconda.com/free/anacondaorg/user-guide/work-with-labels/)'
    default: 'main'
runs:
  using: 'docker'
  image: 'Dockerfile'
