name: 'Publish Conda'
description: 'Build and Publish Conda package to Anaconda'
author: 'Fatih C Akyon; Heliton Martins'
branding:
  icon: 'package'  
  color: 'purple'
inputs: 
  anacondatoken:
    description: 'Anaconda access token'
  platforms:
    description: 'Platforms to publish [osx/linux/win]'
    default: 'win osx linux'
  additional_params:
    description: 'Additional parameters to pass to conda build. See conda build --help for more information.'
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
