name: Publish Conda Package

on: 
  release:
    types: [published, edited]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: publish-to-conda
      uses: hellmrf/conda-publish-action@master
      with:
        subdir: 'conda'
        anacondatoken: ${{ secrets.ANACONDA_TOKEN }}
        additional_channels: "-c pytorch -c helitonmrf"
        platforms: 'win osx linux'